#!/bin/bash -ex
#
# Find any file in /var/lib/snapd/cache with only one link (e.g. it isn't
# hardlinked to /var/lib/snapd/snaps) and an mtime older than a week ago.
#

find /var/lib/snapd/cache/ -type f -links 1 -mtime +7 -exec rm -v '{}' ';'
