#!/bin/sh -e
#
# Removes common cache directories.
#
# This moves files individually, and avoids moving recently created files.
#

MV_OPTIONS="v"
if [ $(uname) = "FreeBSD" ] ; then
	MV_OPTIONS="nv"
fi

DATESPEC=$(date +"%Y%m%d-%H%M")
TRASH="/tmp/trash-${USER}-${DATESPEC}"
MINTIME=15 # minutes

CLEANUP_DIR="
	${HOME}/.cache
"

for i in $(echo ${CLEANUP_DIR}) ; do
	echo "Cleaning up $i"
	if [ ! -e $i ] ; then
		continue
	fi
	find $i -type d -exec mkdir -pv ${TRASH}\{\} \;
	find $i -type f -mmin $MINTIME -exec mv -$MV_OPTIONS \{\} ${TRASH}\{\} \;

	COUNT=1
	while [ -n "$(find $i -mindepth 1 -type d -empty | head -1)" ] ; do
		echo "cleaning empty directories (round $COUNT)"
		find $i -mindepth 1 -type d -empty -exec rmdir '{}' ';' || true
		COUNT=$(($COUNT+1))
	done
done

if [ -x /usr/bin/gio ] ; then
	/usr/bin/gio trash $TRASH
fi
