#!/bin/bash -e
#
# Write a bunch of small files to a temp directory, to slowly fill up a disk's
# metadata (inode table).
#
# You can clean this up with `disk-remove-random-files` or
# `rm -rf fill-disk-metadata-work-*`.
#

random_filename() {
	test -x /usr/bin/uuid && /usr/bin/uuid -v 4 -m && exit
	test -x /usr/bin/uuidgen && /usr/bin/uuidgen -r && exit
	echo "$(date)" $RANDOM | sha256sum | cut -c1-24
}

WORK=fill-disk-metadata-work-$(random_filename | sed -e's/-//' | cut -c1-16)
mkdir -p "$WORK"

BLOCKSIZE=4096
SLEEP=0.1
SOURCE=/dev/zero
OFFSET=0
SYNC=500

while true ; do
	OFFSET=$((OFFSET+1))
	SUB=$(random_filename | cut -c1-2)
	mkdir -p "$WORK"/"$SUB"

	FILE=random-$(random_filename).yyz
	COUNT=1
	echo copying $COUNT $BLOCKSIZE byte blocks from "$SOURCE" to "$SUB"/"$FILE"

	dd if="$SOURCE" of="$WORK"/"$SUB"/"$FILE" bs=$BLOCKSIZE count=$COUNT
	sleep $SLEEP

	if [ -f "$WORK"/stop ] ; then
		rm "$WORK"/stop
		exit
	fi

	if [ $((OFFSET % SYNC)) = 0 ] ; then
		sleep $SLEEP
		sync
		df -h
	fi
done
