#!/bin/sh -e
#
# Tells the Linux kernel to drop (clear) the filesystem caches.
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

TARGET=/proc/sys/vm/drop_caches

if [ -f "$TARGET" ] ; then
	echo 3 > "$TARGET"
else
	echo "Can't drop caches on this system"
	exit 1
fi
