#!/usr/bin/env bash
#
# Looks for a DOS CRLF in code.
#
# There's at least one hit in the composer package squizlabs/php_codesniffer.
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

REGEX='.*[.](c|css|h|html?|inc|java|js|md|php3?|pl|sass|sh|sql|tpl|txt)$'

find . -type f -regextype "posix-extended" -regex "$REGEX" -not -path "*/node_modules/*" -not -path '*/vendor/*' -not -path '*/var/cache/*' | while read -r FILENAME ; do
	RES=$(hexdump "$FILENAME" | cut -f 2- -d " " | grep -cE "( 0a0d )|(0a 0d)")
	if [ "$RES" -gt 0 ] ; then
		echo "$FILENAME"
	fi
done
