#!/bin/sh -e
#
# Stupid, simple script to generate random PINs
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

if [ -n "$1" ] ; then
	NUM=$1
else
	NUM=4
fi

apg -a 1 -M n -n 20 -m "$NUM" -x "$NUM"
