#!/usr/bin/env php
<?php
/**
 * Generates a random PHP password, and dumps the hash of the password.
 *
 * This is intended for TESTING purposes only.
 *
 * -------------------------------------------------------[ Legal Stuff ]-----
 *
 * (c) Doug Harple <dharple@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$source = '/usr/bin/diceware';

$algorithm = PASSWORD_DEFAULT;

$password = exec($source);
$hash = password_hash($password, $algorithm);

printf("%s\n", str_repeat('-', 79));

printf("source: %s\n", $source);

printf("%s\n", str_repeat('-', 79));

printf("password: %s\n", $password);
printf("hash: %s\n", $hash);

$info = password_get_info($hash);
printf("algorithm: %s\n", $info['algoName']);

printf("%s\n", str_repeat('-', 79));

// vim:ai:cin:et:ts=4:sw=4:fo+=or
