#!/usr/bin/env php
<?php

$source = '/usr/bin/diceware';

$algorithm = PASSWORD_DEFAULT;

$password = exec($source);
$hash = password_hash($password, $algorithm);

printf("%s\n", str_repeat('-', 79));

printf("source: %s\n", $source);

printf("%s\n", str_repeat('-', 79));

printf("password: %s\n", $password);
printf("hash: %s\n", $hash);

$info = password_get_info($hash);
printf("algorithm: %s\n", $info['algoName']);

printf("%s\n", str_repeat('-', 79));
