#!/bin/sh -e
#
# Show changed files for some other script to review
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

git diff --name-only --diff-filter=ACMR $@
