#!/bin/sh -e
#
# Removes any remote branches that have been removed on the remote repository.
#
# Runs git garbage collection.
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

git fetch --all --prune
git gc
