#!/bin/sh -e
#
# Runs `git gc` on both the local directory, and the repository, iff the
# repository is a locally accessible directory.
#
# If a fix-perms script exists, run that, too.
#

sync
git gc
if [ -x ./fix-perms ] ; then
	./fix-perms
fi

REMOTE=$(git config --get remote.origin.url)
if [ -d "$REMOTE" ] ; then
	cd "$REMOTE"
	git gc
fi
