#!/bin/sh
#
# Recursive git (and composer).
#
# Run `gitr status` or `gitr composer info` for a non-destructive preview.
#

BASE=$(pwd)
for GITDIR in $(find -type d -name .git -not -path '*/vendor/*') ; do
	REPODIR=$(dirname $GITDIR)
	echo -------------------------------------
	echo $REPODIR
	echo -------------------------------------
	echo

	cd $BASE/$REPODIR

	if [ -f .git/skip-gitr ] ; then
		echo "gitr disabled in this repo"
		echo
		continue
	fi

	if [ "$1" = "composer" ] ; then
		if [ -f composer.json ] ; then
			$@
		fi
	else
		git $@
	fi

	echo
done
