#!/usr/bin/env bash
#
# Recursive git (and composer).
#
# Run `gitr status` or `gitr composer info` for a non-destructive preview.
#

function banner()
{
	echo -------------------------------------
	echo "$1"
	echo -------------------------------------
	echo
}

if [ -z "$VERBOSE" ] ; then
	VERBOSE=0
fi

SKIPFILE=.git/skip-gitr

BASE=$(pwd)
for GITDIR in $(find . -maxdepth 3 -type d -name .git -not -path '*/vendor/*' -not -path '*/.symfony/*') ; do
	REPODIR=$(dirname "$GITDIR")

	cd "$BASE"/"$REPODIR" || exit


	if [ "$1" = "skip" ] ; then
		banner "$REPODIR"

		case "$2" in
			disable)
				if [ -f $SKIPFILE ] ; then
					rm -f $SKIPFILE
					echo "gitr skip is now disabled"
				else
					echo "gitr skip is already disabled"
				fi
			;;

			enable)
				if [ ! -f $SKIPFILE ] ; then
					touch $SKIPFILE
					echo "gitr skip is now enabled"
				else
					echo "gitr skip is already enabled"
				fi

			;;

			status)
				if [ -f $SKIPFILE ] ; then
					if [ "$VERBOSE" -gt 0 ] ; then
						echo "gitr skip is enabled in this repo"
						echo -n "... "
					fi
					echo "this repo is ignored by gitr"
				else
					if [ "$VERBOSE" -gt 0 ] ; then
						echo "gitr skip is disabled in this repo"
					fi
				fi
			;;

			*)
				echo "usage:"
				echo "	gitr skip (disable|enable|status)"
			;;
		esac

		echo

		continue
	fi

	if [ -f $SKIPFILE ] ; then
		if [ "$VERBOSE" -gt 0 ] ; then
			banner "$REPODIR"
			echo "gitr disabled in this repo"
			echo
		fi

		continue
	fi

	banner "$REPODIR"

	if [ "$1" = "composer" -o "$1" = "symfony" ] ; then
		if [ -f composer.json ] ; then
			"$@"
		fi
	elif [ "$1" = "npm" ] ; then
		if [ -f package.json ] ; then
			"$@"
		fi
	else
		git "$@"
	fi

	echo
done
