#!/usr/bin/env php
<?php
//
// Looks for hidden UTF-8 characters.
//

function usage()
{
    fprintf(STDERR, "Usage:\n\t%s [FILE]\n", $GLOBALS['argv'][0]);
    exit(-1);
}

if ($argc === 1 || ($argc > 1 && $argv[1] == '-')) {
    $file = 'php://stdin';
} else {
    $file = $argv[1];
    if (!file_exists($file)) {
        usage();
    }
}

$expression = exec(realpath(__DIR__) . DIRECTORY_SEPARATOR . 'build-hidden-utf8-pcre');

//

$blockSize = 65536;

$fp = fopen($file, 'r');
if ($fp === false) {
    fprintf(STDERR, "could not read file '%s'\n", $file);
    exit(-2);
}

$hiddenCount = 0;
while ($contents = fgets($fp, $blockSize)) {
    if (preg_match_all($expression, $contents, $matches)) {
        $hiddenCount += count($matches[0]);
    }
}

if ($hiddenCount < 10) {
    exit(1);
}

fprintf(STDERR, "file '%s' has %d hidden UTF-8 characters\n", $file, $hiddenCount);

fclose($fp);

exit(0);

// vim:ai:cin:et:ts=4:sw=4:fo+=or
