#!/bin/sh -e
#
# Draw the year and month, in the form YYYYMM.
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

date +"%Y%m"
