#!/bin/sh -e
#
# Splits files in the format "Y-m-d*" into Y/m/ subdirectories.
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

ls

echo "Organize this directory?  Type 'yes' to continue."
read CHECK

if [ "$CHECK" != "yes" ] ; then
	exit 0
fi

for PREFIX in $(find . -maxdepth 1 -mindepth 1 -type f | cut -f 1-2 -d - | sort | uniq) ; do
	DIR=$(echo "$PREFIX" | sed -e's@-@/@')
	echo ----------------------------------------------------
	mkdir -p "$DIR"
	mv -iv "$PREFIX"-* "$DIR"
done
