#!/usr/bin/env php
<?php
/**
 * Run PHP's unserialize against STDIN.
 *
 * -------------------------------------------------------[ Legal Stuff ]-----
 *
 * (c) Doug Harple <dharple@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$data = file_get_contents('php://stdin');
print_r(unserialize($data));

// vim:ai:cin:et:ts=4:sw=4:fo+=or
