#!/bin/sh
#
# Removes GPS data from an image.
#
# --------------------------------------------------------[ Legal Stuff ]-----
#
# (c) Doug Harple <dharple@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

exiftool -gps:all= $@
