#!/bin/bash -e
#
# Keeps removing random files until you tell it to stop.
#
# Pass `--fast` to make the script run faster.
#
# This will remove *any* file in the current directory of below that matches
# 'random-*.yyz'.  Use with caution.
#

MAXSLEEP=5 # seconds
FAST=0
if [ -n "$1" -a "$1" = "--fast" ] ; then
	FAST=1
fi

while [ 1 ] ; do
	FILE=$(find -type f -name 'random-*.yyz' | shuf | head -1)

	if [ -z "$FILE" ] ; then
		echo nothing to remove
	else
		if [ ! -f "$FILE" ] ; then
			echo "something went wrong; found then lost $FILE"
			exit 1
		fi

		date
		echo removing $FILE
		rm "$FILE"
	fi

	if [ "$FAST" = "0" ] ; then
		sleep $(($RANDOM % $MAXSLEEP))
	else
		sleep 0.1
	fi

done

