#!/bin/sh
#
# Starts basic services, and runs some cleanup.
#

SCRIPT=$(dirname $0)/cleanup-ssh
if [ -x $SCRIPT ] ; then
	$SCRIPT
fi

if [ -x /usr/sbin/service ] ; then
	/usr/sbin/service rsyslog start
	/usr/sbin/service redis-server start || echo redis is not installed
	/usr/sbin/service mysql start || echo mysql is not installed
	/usr/sbin/service cron start

	# initialize /run/screen
	/usr/sbin/service screen-cleanup start
fi

# run anacron
if [ -x /usr/sbin/anacron ] ; then
	/usr/sbin/anacron -s -n
else
	echo anacron is not enabled
fi
